project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Bo Laurent"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: about.qmd
            text: About Bo
          - href: colophon.qmd
            text: Colophon
      - href: blog/index.qmd
        text: Writing
      - href: blog/news/index.qmd
        text: News
      - href: blog/japanese/index.qmd
        text: Japanese
      - href: blog/komonjo/index.qmd
        text: 古文書
      - href: blog/intersex/index.qmd
        text: Intersex
    right:
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: litera
    css: styles.css

