project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Bo Laurent"
  google-analytics: "G-GSLYJ6M3RE"
  favicon: images/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: about.qmd
            text: About Bo
          - href: colophon.qmd
            text: Colophon
      - href: blog/japanese.qmd
        text: Japanese
      - href: blog/intersex.qmd
        text: Intersex
    right:
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: litera
    css: styles.css

