---
title: "摩訶不思議の病気「江戸患い」"
description: "日本の歴史において白米が多くの人々に病をもたらした"
date: 2026-06-22
draft: true
categories: [japanese, writing]
---

# 摩訶不思議の病気「江戸患い」

日本の食生活を考えると、つい白米が思い浮かぶだろう。自国がお米の生産において自給自足できていることを誇りに思っている。しかし、日本の歴史において白米が多くの人々に病をもたらしたことは、あまり知られていない。江戸時代の参勤交代で江戸に滞在していた侍たちは、「江戸患い」とよばれる病気に悩まされた。帰郷するとただちに治ることが特徴だった。最悪の場合、死に至ることもあるほど重大な病気だった。徳川家の将軍のうち、4人がその病気（脚気）によって亡くなったと考えられている。明治天皇とその親戚も脚気で悩み続けたという。

当時、その原因は不明だったが、現代ではビタミンB1の不足による病気であると解明されている。玄米を白米に加工すると、ビタミンB1が取り除かれる。機械化によって白米が広く普及するようになると、脚気は深刻な社会問題に発展した。特に、海軍や陸軍が影響を受けた。白米は兵隊に好まれるだけではなく、玄米より保存が効くため、軍隊で優先的に食べられていたからだ。

海軍では、医者高木兼寛が多様な給食メニューにすることで脚気を抑えることができると実験によって証明して以降、脚気問題は1890年からほぼなくなった。しかし陸軍の指導者はその証明に抵抗し、受け入れなかった。それにより、陸軍だけ脚気による死亡者数が増加した。日清戦争の戦死者の800人に対し、脚気死亡者数は1万人を超えた。

さらに、西洋で1889年に精米が脚気を起こすことが証明された。それにもかかわらず、日本で脚気の原因については議論だけが長く続けられ、なかなか解決に至らなかった。1927年に脚気が食生活上のビタミンB1不足に原因があると日本政府がようやく認めた。

現在、過去の日本の生活が純粋で健康的だったと思う傾向が顕著である。しかし、科学研究の成果について私たちはあまりにも知らなすぎる。私たちが受け継いだ世界は、過去と比べてさまざまな面で豊かで安全であることを意識してほしい。大量の情報に振り回されがちだが、根拠のある研究成果についてしっかり調べることが重要だ。
